### ISSUE TITLE
Issue with preparing dataset failed：The dataset preparation failure caused by the Ianvs project update

### ISSUE THREAD

**Issue by LQS082** [kubeedge/ianvs#164]
**What happened**:
As my title suggests, I encountered a **dataset preparation error** due to updates in the Ianvs project while running a example in the Ianvs project. Here is the entire process of encountering the problem, my solution, and the cause of the problem. I hope this can help others who have also encountered the same problem.
About a month ago, I started trying to run the Example Cloud-Robotics-1 case, and about half a month ago, after obtaining the required dataset from @hsj576 , I found that the device I was using was not sufficient to achieve the performance required for the case.
Later, I switched to another device and pulled Ianvs' project files from GitHub again to prepare for running Example Cloud-Robotics-1.However, during the configuration process, I encountered an error of dataset preparation failure as shown below. 
``` 
Traceback (most recent call last):
  File "/usr/local/bin/ianvs", line 33, in <module>
    sys.exit(load_entry_point('ianvs==0.1.0', 'console_scripts', 'ianvs')())
  File "/usr/local/lib/python3.10/dist-packages/ianvs-0.1.0-py3.10.egg/core/cmd/benchmarking.py", line 41, in main
    raise RuntimeError(f"benchmarkingjob runs failed, error: {err}.") from err
RuntimeError: benchmarkingjob runs failed, error: prepare dataset failed, error: not one of train_index/train_data/train_data_info..

```
This problem did not occur during the previous configuration process, and after repeatedly changing the path and file placement path in the YAML file, the issue has not been resolved.

After being troubled by this issue for two weeks, I accidentally discovered that the testenvmanager folder in the Ianv project had been changed two weeks ago, so **I switched to using the Ianvs project package pulled from GitHub a month ago to run Example Cloud-Robotics-1.** At this point, the problem of dataset preparation failure no longer exists.
Through communication with @hsj576 , I have learned that the reason for the error may have come from the integration of kubeedge Ianvs into this year's open source summer project code half a month ago, and the updated code may not be compatible with the previous example.

**What you expected to happen**:
    I hope my findings can help classmates who encounter similar problems, and I also hope that my findings can help the project team further improve the project documentation.

**Comment by MooreZheng** [comment]
The hard work is highly appreciated! It preliminarily finds the cause of this issue on testenvmanager. We also encourage @LQS082 to keep locating the exact function that leads to the bug, by comparing and replacing codes between the two versions. That could be a critical contribution to the ianvs core.

**Comment by AryanNanda17** [comment]
@LQS082, in your testenv.yml file try changing `train_url` to `train_index` and `test_url` to `test_index`. 
The error should be resolved by doing that.
