### ISSUE TITLE
Couldn't run example in scene-based-unknown-task-recognition

### ISSUE THREAD

**Issue by hsj576** [kubeedge/ianvs#56]
**What happened**:
I followed every instructions in the Quick Start of scene-based-unknown-task-recognition, I am pretty sure that I installed the feature-lifelong-n branch of Ianvs successfully, but I still couldn't run the example.

The log information is as follow:

un_classes:24
Upsample layer: in = 128, skip = 64, out = 128
Upsample layer: in = 128, skip = 128, out = 128
Upsample layer: in = 128, skip = 256, out = 128
128
Model loaded successfully!
Traceback (most recent call last):
  File "/ianvs/project/ianvs/core/testcasecontroller/testcase/testcase.py", line 74, in run
    res, system_metric_info = paradigm.run()
  File "/ianvs/project/ianvs/core/testcasecontroller/algorithm/paradigm/lifelong_learning/lifelong_learning.py", line 91, in run
    self.cloud_task_index = self._train(self.cloud_task_index,
  File "/ianvs/project/ianvs/core/testcasecontroller/algorithm/paradigm/lifelong_learning/lifelong_learning.py", line 185, in _train
    job = self.build_paradigm_job(ParadigmType.LIFELONG_LEARNING.value)
  File "/ianvs/project/ianvs/core/testcasecontroller/algorithm/paradigm/base.py", line 103, in build_paradigm_job
    return LifelongLearning(
  File "/root/miniconda3/lib/python3.8/site-packages/sedna/core/lifelong_learning/lifelong_learning.py", line 146, in __init__
    self.unseen_sample_recognition.get("param", {}))
AttributeError: 'UnseenSampleRecognitionByScene' object has no attribute 'get'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ianvs/project/ianvs/core/testcasecontroller/testcasecontroller.py", line 54, in run_testcases
    res, time = (testcase.run(workspace), utils.get_local_time())
  File "/ianvs/project/ianvs/core/testcasecontroller/testcase/testcase.py", line 79, in run
    raise Exception(
Exception: (paradigm=lifelonglearning) pipeline runs failed, error: 'UnseenSampleRecognitionByScene' object has no attribute 'get'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ianvs/project/ianvs/core/cmd/benchmarking.py", line 37, in main
    job.run()
  File "/ianvs/project/ianvs/core/cmd/obj/benchmarkingjob.py", line 88, in run
    succeed_testcases, test_results = self.testcase_controller.run_testcases(self.workspace)
  File "/ianvs/project/ianvs/core/testcasecontroller/testcasecontroller.py", line 56, in run_testcases
    raise Exception(f"testcase(id={testcase.id}) runs failed, error: {err}") from err
Exception: testcase(id=8fe90ddc-b903-11ed-bbd3-02420a00300a) runs failed, error: (paradigm=lifelonglearning) pipeline runs failed, error: 'UnseenSampleRecognitionByScene' object has no attribute 'get'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/bin/ianvs", line 33, in <module>
    sys.exit(load_entry_point('ianvs==0.1.0', 'console_scripts', 'ianvs')())
  File "/ianvs/project/ianvs/core/cmd/benchmarking.py", line 41, in main
    raise Exception(f"benchmarkingjob runs failed, error: {err}.") from err
Exception: benchmarkingjob runs failed, error: testcase(id=8fe90ddc-b903-11ed-bbd3-02420a00300a) runs failed, error: (paradigm=lifelonglearning) pipeline runs failed, error: 'UnseenSampleRecognitionByScene' object has no attribute 'get'.

**Anything else we need to know?**:
The environment is Ubuntu18.04, python3.8.5

**Comment by MooreZheng** [comment]
Would this error be fixed in https://github.com/kubeedge/ianvs/pull/65?

**Comment by hsj576** [comment]
> Would this error be fixed in #65?

No.
