### ISSUE TITLE
Couldn't run example in curb-detection/lifelong_learning_bench

### ISSUE THREAD

**Issue by hsj576** [kubeedge/ianvs#57]
**What happened**:
I tried to run the example in curb-detection/lifelong_learning_bench. I followed every instructions in Quick Start. It went well in the training part and evaluation part, but when it came to the inference part, an error was occurred. 

The log information was as follows:
[2023-03-02 22:20:31,947] task_evaluation.py(69) [INFO] - real_semantic_segamentation_model scores: {'accuracy': 0.13164643646434354}
[2023-03-02 22:20:31,966] lifelong_learning.py(395) [INFO] - Task evaluation finishes.
[2023-03-02 22:20:31,967] lifelong_learning.py(398) [INFO] - upload kb index from index.pkl to /ianvs/lifelong_learning_bench/workspace/benchmarkingjob/rfnet_lifelong_learning/ef4da0e4-b903-11ed-bb65-02420a00300a/output/eval/1/index.pkl
Traceback (most recent call last):
  File "/ianvs/project/ianvs/core/testcasecontroller/testcase/testcase.py", line 74, in run
    res, system_metric_info = paradigm.run()
  File "/ianvs/project/ianvs/core/testcasecontroller/algorithm/paradigm/lifelong_learning/lifelong_learning.py", line 100, in run
    inference_results, unseen_task_train_samples = self._inference(
  File "/ianvs/project/ianvs/core/testcasecontroller/algorithm/paradigm/lifelong_learning/lifelong_learning.py", line 153, in _inference
    res, is_unseen_task, _ = job.inference(data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/sedna/core/lifelong_learning/lifelong_learning.py", line 453, in inference
    seen_samples, unseen_samples = unseen_sample_recognition(
TypeError: __call__() got an unexpected keyword argument 'mode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ianvs/project/ianvs/core/testcasecontroller/testcasecontroller.py", line 54, in run_testcases
    res, time = (testcase.run(workspace), utils.get_local_time())
  File "/ianvs/project/ianvs/core/testcasecontroller/testcase/testcase.py", line 79, in run
    raise Exception(
Exception: (paradigm=lifelonglearning) pipeline runs failed, error: __call__() got an unexpected keyword argument 'mode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ianvs/project/ianvs/core/cmd/benchmarking.py", line 37, in main
    job.run()
  File "/ianvs/project/ianvs/core/cmd/obj/benchmarkingjob.py", line 88, in run
    succeed_testcases, test_results = self.testcase_controller.run_testcases(self.workspace)
  File "/ianvs/project/ianvs/core/testcasecontroller/testcasecontroller.py", line 56, in run_testcases
    raise Exception(f"testcase(id={testcase.id}) runs failed, error: {err}") from err
Exception: testcase(id=ef4da0e4-b903-11ed-bb65-02420a00300a) runs failed, error: (paradigm=lifelonglearning) pipeline runs failed, error: __call__() got an unexpected keyword argument 'mode'

**Anything else we need to know?**:
The environment is Ubuntu18.04, python3.8.5

**Comment by MooreZheng** [comment]
This issue seems to be fixed with PR https://github.com/kubeedge/ianvs/pull/63
