### ISSUE TITLE
运行reid_job示例时候报错，有遇到过吗

### ISSUE THREAD

**Issue by wwwjustin** [kubeedge/ianvs#93]
Traceback (most recent call last):
  File "/root/miniconda3/envs/py38/bin/ianvs", line 33, in <module>
    sys.exit(load_entry_point('ianvs==0.1.0', 'console_scripts', 'ianvs')())
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/ianvs-0.1.0-py3.8.egg/core/cmd/benchmarking.py", line 37, in main
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/ianvs-0.1.0-py3.8.egg/core/cmd/obj/benchmarkingjob.py", line 93, in run
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/ianvs-0.1.0-py3.8.egg/core/testcasecontroller/testcasecontroller.py", line 58, in run_testcases
RuntimeError: testcase(id=eac637fa-c124-11ee-b0ba-694f39bcabcf) runs failed, error: (paradigm=multiedgeinference) pipeline runs failed, error: 'MultiedgeInference' object has no attribute 'modules_funcs'

**Comment by wyoung1** [comment]
same question, did you solve it?
